packages:
  - 'functions'
allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-ssm@3.1133.0'
  - '@types/node@24.13.5'
  - google-auth-library@11.1.0
  - '@google/genai@2.23.0'
